### ISSUE TITLE
Загрузка файла

### ISSUE THREAD

**Issue by xerasy** [Nirklav/TCPChat#10]
Добрый день, не подскажите, в какую сторону копать, проблема вот в чем : при попытке загрузить файл в комнату `client.AddFileToRoomAsyc($"Main room", newfilename);` Выдает ошибку "пользователь уже раздает этот файл", хотя этот файл я гружу впервые, проблема решается перезапуском сервера или нужно добавить файл в комнату, потом убрать его с раздающих и опять добавить. Не подскажите, где может быть проблема ? 

п.с Использую версию 1,5, т.к не хочу с ехе тащить еще длл

**Comment by Nirklav** [comment]
Привет!
Там просто могут быть баги, нужно смотреть реализацию команды на сервере. Я бы просто посоветовал использовать последнюю версию. Во первых если там обнаружистя баг то я его исправлю. А во вторых там больше функционала.

**Comment by xerasy** [comment]
можете плз глянуть ? я не могу использовать посл версию по нескольким причинам : 
1. Нужно тащить за собой дллки, если engine.dll можно еще "убрать", то другую нет
2. Версия 1.5 идеально подходит под мои цели, а в последующих очень много "лишних" функций 

Если вы поможете с этой версий, то я в долгу не останусь , спасибо

**Comment by Nirklav** [comment]
Там были проблемы с тем, что у описания файла не составной идентификатор, то есть файлы от разных юзеров могли пересекаться, нужно сделать как в последней версии чата. Также баг может быть в закрытии комнаты, если файл все комнаты закрыты то файл нужно тоже выгружать.

**Comment by xerasy** [comment]
понял, спасибо, ща попытаюсь что-то сделать. Кстати, вы рассматриваете фикс версии 1,5 за денежное вознаграждение ? мне щас долго есть разбираться в коде, а вам нет, если есть такая возможность, то это сильно бы мне упростило задачу, спасибо

**Comment by xerasy** [comment]
админом главной комнаты является главный сервер ? у меня тут пришла мысль, может сделать, чтоб сервер сам выгружал все файлы через n время, такое возможно ? помнится, что у меня как-то была ошибка, что недостаточно прав для выгрузки файла, но тогда я пробовал не от сервера

**Comment by Nirklav** [comment]
> Кстати, вы рассматриваете фикс версии 1,5 за денежное вознаграждение ?
Нет, не рассматриваю. У меня нет времени заниматься этой работой. Все таки посмотрите на возможность использовать последнюю версию. Причина о том, что имеет он один файл или несколько кажется мне невероятно странной.
