### ISSUE TITLE
Использование как встраиваемый плагин

### ISSUE THREAD

**Issue by Serg-Norseman** [Nirklav/TCPChat#12]
Здравствуйте! Очень нравится ваш проект и давно посматриваю как идет разработка. Есть такие вопросы: 
- Возможно ли использовать ваш проект, в качестве встраиваемого модуля (плагина) в рамках другого проекта?
- Можно ли присоединиться, если будут какие-то идеи для улучшения или дополнения?
- При желании сделать кросс-платформенный клиент на базе Eto-фреймворка - это лучше будет делать только в форке, или вы примете такой клиент (как альтернативный) в основной проект (может кто-нибудь еще сделает клиент на базе Avalonia или XWT)?
- Самое интересное для меня: можно ли сделать дополнительную P2P фичу - обнаружение пирами друг друга на основе DHT или другой основе, чтобы не иметь специализированного сервера вообще?
- Возможно ли сделать на базе протокола вашего проекта такой плагин (плагин чата, работающий параллельно с ним), чтобы передавать сильно специализированную информацию (не файлы, и не сообщения или звук)?

**Comment by Nirklav** [comment]
Здравствуйте!

- Я думаю это реализуемо.
- Да, буду рад рассмотреть дополнения или улучшения.
- С кроссплатформеностью есть небольшие проблемы, но я думаю с ними можно будет разобраться. Например .net standard не поддерживает домены приложения, и плагины придется делать не выгружаемыми и без песочницы. Также у текущего сериализатора еще не полностью реализована поддержка стандарта, опять же из за доменов.
- Целью скорее является сеть независимых серверов, где пользователи могут выбирать на каком из них они могут общаться. Именно для этого я сейчас реализую поддержку сертификатов, что бы пользователи могли определить друг друга и безопасно общаться на любом из серверов.
- Да возможно, но код придется достаточно сильно почистить.

Надеюсь, что ответил на все вопросы. Если нет, то уточняйте.

**Comment by Serg-Norseman** [comment]
Большое спасибо за ваши ответы! Очень обнадежили!

Я пока сам затрудняюсь определить, что могу реализовать полезного. Т.к. конечно в наибольшей степени заинтересован в своей задаче и её сложно вот так сразу сформулировать. Но зато я совершенно не хочу разрабатывать свой самопальный, кривой и примитивный велосипед, поэтому и захотел участвовать в правильном проекте, который можно было совместно улучшать и применять.

В моём проекте у меня следующая идея: есть моя программа (далее условный "хост"), в которой пользователи работают со своими данными, которые иногда могут пересекаться с данными других пользователей. Я заинтересован в том, чтобы у этих пользователей была возможность активировать в программе-хосте специальный плагин для связи, который предоставит три следующих важных функции: во-первых, пользователи могут видеть список тех, кто также в это-же время работают с программой, во-вторых - пользователи могут найти и вступить в связь со своими друзьями или коллегами и обменяться мнениями, решить какие-то вопросы, обменяться информацией - всё это через чат. И наконец, третье, на базе вспомогательного протокола (параллельного чату), пользователь может пометить какие-то записи в своей базе данных как видимые для поиска извне другими пирами этой сети (как-бы поместить данные на "доску объявлений"), соответственно также будет и функция поиска по этой "доске объявлений". Всё это нужно мне для того, чтобы не создавать параллельных программе веб-сервисов, сайтов, онлайн-баз данных и форумов. Чтобы был комплексный сервис в одном месте, в одной программе.

Про DHT-обнаружение я написал потому, что очень сильно не хочу держать где-либо хоть какой-то свой сервер для поддержания сети пиров моей программы. Ну это моя мечта такая, может несерьезная. И в настоящее время, не концентрируясь на задачах чата и протокола, я занимаюсь исследованием возможных подходов. Похвастать пока нечем, но я не теряю надежды. Основная идея в том, чтобы построить bootstrap-процедуру на базе BittorrentDHT-серверов для первичного поиска запущенных пиров, чтобы они находили друг друга на первой стадии и затем работали уже самостоятельно и независимо.

Соответственно, хотелось бы также такую возможность: при использовании TCPChat как плагина - иметь дополнительную внутреннюю сигнатуру на уровне протокола или реализации ядра чата, которая позволяла бы пользователям моей программы изначально находиться в своей изолированной "комнате", не пересекаясь с другими. Соответственно, если кто-то использует TCPChat как автономную программу - такая опция (что-то типа свойства SubnetworkSign) по дефолту выключена и все находятся в одной общей сети. Возможно всё это я криво сформулировал.

Также про эти фичи хочу сказать, что ни в коем случае не претендую на какой-то один подход, но полностью за максимальную гибкость и возможность переключаться между различными возможностями.
