### ISSUE TITLE
Program can't initialize sound devices

### ISSUE THREAD

**Issue by grishakonzalaev** [Nirklav/TCPChat#14]
Notebook: Lenovo g480
OS: windows10 1803
Last release.
I don't see my microphone and headphones in settings.
If I close settings or connect to server, I see this dialog: Audio system not initialized. Voice chat disabled.

**Comment by Nirklav** [comment]
Hello, you should install OpenAL library from official site.

https://www.openal.org/downloads/

**Comment by grishakonzalaev** [comment]
Thank you. Sorry for my bad attention. All works fine!
Please make warning about installing this library in next version. It will cool!
