### ISSUE TITLE
Error in input values

### ISSUE THREAD

**Issue by ReKtWolf** [Nirklav/TCPChat#15]
No matter what i do when i try to create a server it just closes the window and says "Error in input values".This didn't happen in the pre-certificate versions. I have a feeling that I've missed something obvious but if not a guide on how to create your own servers properly would help.

**Comment by Nirklav** [comment]
Hi!

Would you describe steps to reproduce this case?

**Comment by ReKtWolf** [comment]
I click "Enable Server" put in my routers public ip and a port i've forwarded, i choose a certificate i've created with the same ip and put in the password i wrote in the certificate. But when i click "Accept" it closes the window and this message comes up 

![image](https://user-images.githubusercontent.com/49165799/55431471-4b1c1680-5599-11e9-8154-a8db9097c784.png)

Which inputs did I mess up?

**Comment by Nirklav** [comment]
I think certificate address and server address does not match.
What value you type in certificate server address field?
And what address you use to starts server?

P.S. Im implement normal error messages soon..

**Comment by mananhfz** [comment]
Server Address: 0.0.0.0:10021
The Certificate is in the same local directory where I have my exe file. Its still says error in input values.

**Comment by Nirklav** [comment]
Server can't work with address 0.0.0.0, you should start server with same ip that you was entered in certificate.

**Comment by DanielVampire** [comment]
Привет. Наткнулся на твой проект, выглядит весьма интересно. Как раз разбираюсь с p2p, по этому решил рассмотреть на твоем примере. Вот тут такой вопрос: когда запускаю сервер в локальной сети - все работает хорошо, но если я прописываю публичный статический IP, с сертификатом под этот IP, то получаю ошибку:
![image](https://user-images.githubusercontent.com/22197122/124730405-fb67ea80-df19-11eb-9f36-1e7d053c9219.png)

По коду увидел, что по идее этот адрес Bind в сокете и выступает как LocalEndPoint и вот в этом месте и происходит исключение. Подскажи, пожалуйста, что нужно предпринять, возможно настройки какие изменить. (Брандмауэр отключен вообще, на всякий).

Спасибо за ответ)

**Comment by Nirklav** [comment]
@DanielVampire скинь логи ошибок пожалуйста. Или их там нету? Если нету то собщение и стек трейс ошибки.

**Comment by DanielVampire** [comment]
Смотри, там исключение от сокета вылазит с сообщением "требуемый адрес для
своего контекста не верен". В логах сервака пусто и в файле других ошибок
тоже пусто.
То есть там когда делаем bind в сокет выходит исключение.
Могу на видео записать весь процесс в принципе.

вс, 11 июл. 2021 г., 12:43 PM Anton ***@***.***>:

**Comment by DanielVampire** [comment]
Сейчас скину stack trace

пн, 12 июл. 2021 г., 10:08 AM Daniel Mentjak ***@***.***>:

**Comment by DanielVampire** [comment]
файл NetPeer.Internal, 121 строка. делаем Bind и ловим: Вызвано исключение: "System.Net.Sockets.SocketException" в System.dll
![image](https://user-images.githubusercontent.com/22197122/125246317-5030aa00-e2fa-11eb-921b-f8f31cd1d1e3.png)
![image](https://user-images.githubusercontent.com/22197122/125246684-c7663e00-e2fa-11eb-856a-8b4c6bb22395.png)

StackTrace = "  at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.Sockets.Socket.Bind(EndPoint localEP)\r\n   at Lidgren.Network.NetPeer.InitializeNetwork() in F:\\Examples\\TCPChat-master\\Lidgren.Network\\NetPeer.Internal.cs:line 122\r\n   at Lidgren.Network.NetPeer.Start() in F:\\Examples\\TCPChat-master\\Lidgren.Network\\NetPeer.cs:line 145\r\n   at Engine.Network.P2PService..ctor(IPAddress address, Int32 port, IApi api, Logger logger) in F:\\Examples\\TCPChat-master\\Engine\\Network\\P2PService.cs:line 85\r\n   at Engine.Network.AsyncServer.StartImpl(IPAddress address) in F:\\Examples\\TCPChat-master\\Engine\\Network\\AsyncServer.cs:line 193\r\n   at Engine.Network.AsyncServer.Start(Uri serverUri, Int32 p2pServicePort) in F:\\Examples\\TCPChat-master\\Engine\\Network\\AsyncServer.cs:line 143"

**Comment by DanielVampire** [comment]
Насколько я понимаю, тут нужно чтобы вводился локальный адрес. Только не особо понимаю как мне тогда из вне постучаться к нему.

**Comment by Nirklav** [comment]
У твоего компьютера точно адрес 94.158.36.78? Если нет, он по этому не может к нему прибиндится. Нужно на маршрутезаторе открывать порт и настривать проброс с этого порта к компьютеру. Сервер можно стартовать с адресом 0.0.0.0 .

**Comment by DanielVampire** [comment]
Я вот сейчас понял что я тупил. Я открыл порт на роутере, тот ip - ip
роутера.
Теперь получается я могу стартовать сервер по этому порту локально, а при
постукивании в роутер по его ip и порту нужному, будет переадресация на мой
комп по этому порту и тогда по идее все должно работать правильно, так?
И спасибо за помощь, туплю несчадно. С сетью не работал ранее от слова
совсем.

пн, 12 июл. 2021 г., 12:53 PM Anton ***@***.***>:

**Comment by DanielVampire** [comment]
@Nirklav Я тебя снова потревожу... В общем, все стартует через глобальный IP, сообщения передаются, файлы передаются. Но, другая проблема: не работает voice chat. Если запускать через локалку, то по логам идут такие команды, как: 
AsyncPeer.ConnectToService(IP)
AsyncPeer.ServiceConnect()
AsyncPeer.WaitConnection(IP)
ClientWaitPeerConnectionCommand

Если же стартовать через глобальный IP, из всех этих последовательных команд срабатывает только первая. Все перелазил, не могу понять в чем причина.
Ну точнее я нашел причину, но не могу понять в чем её начало.
файл Api.Client, метод OnRecorder. В конце вызывается метод SendMessageIfConnected(). В нем идет проверка FindConnection(), который возвращает постоянно null, а в _handler.Connections - постоянно 0 элементов. Если запускаться через локальный IP, то здесь отображаются соединения.

**Comment by Nirklav** [comment]
Проблема на настройках роутера. Нужно проверить что открыт порт который установлен для p2p сервера на роутере, для UDP.
