### ISSUE TITLE
Create voice chat with configured server

### ISSUE THREAD

**Issue by karokarok** [Nirklav/TCPChat#16]
Hello.
First of all, its nice to see your work on this TCP Chat because its work really great.
I am creating a private games that required only Voice Chat.
I would like to request a voicechat window for my games with configured server instead of p2p multiserver. I don't mind if you want to create the voice chat server as opensource.
the simple function i would like to request : 
- Simple login forms with encryption hash sha256 (MYSQL) or others.
- Push button to chat for player configured button or default buttons.
- Make Voice Chat windows forms always appear transparent on the front even players are playing the game.
- Ability to block voice chat in certain time. (for admin)

I can push up some milestone for the project.
Let me know if you are intrested with the project your email/skype or anykind of contact so that i can discuss this matter with you.

**Comment by Nirklav** [comment]
Hi, karokarok!

Unfortunately I don't work on this project now.

Thank you for your request!
