### ISSUE TITLE
Windows Forms

### ISSUE THREAD

**Issue by dsaddddd** [Nirklav/TCPChat#6]
Это не составит труда перестроить для WF? Или там много чего в коде зависимо от библиотек WPF?

**Comment by Nirklav** [comment]
Сама Engine, которая ответственна за логику чата написана без привязки к какому либо UI. И ее без проблем можно подключить, например, к WF.

**Comment by dsaddddd** [comment]
Благодарю за ответ, теперь всё ясно. В исходниках чата пока не копался, но сразу бросилось в глаза WPF с которым дело почти не имел. Всегда сидел на WinForm.
