### ISSUE TITLE
Развитие чата

### ISSUE THREAD

**Issue by Username128** [Nirklav/TCPChat#7]
Привет. Интересует дальнейшая судьба этого чата.

Например:

1) Эмотиконы
2) Аватары
3) Статус (онлайн, оффлайн, отошёл, занят, т.п.)
4) Подпись под ником как во всяких skype'ах
5) "User is typing a message" когда набираешь сообщение
6) Отслеживание сообщений только с определённой комнаты(чтобы не спамило со всех)
7) Больше команд для админа сервера и владельцев комнат: выгнать с сервера, замутить, резервные слоты
8) Создание групп в комнатах(аналогия с TeamSpeak)
8) Какая-то информация о сервере, комнате, группе как в TeamSpeak
9) Если уж говорить о TeamSpeak то почему бы не реализовать схожую систему с использованием public, private key что позволит серверу идентифицировать пользователей и выдавать им их текущие комнаты, группы, etc

Ну и можно всякого добавить. Хотел в общих чертах обрисовать смысл.

**Comment by Nirklav** [comment]
Привет!
Самостоятельно реализовать весь предложенный функционал у меня нет времени.

В ближайшее время я планировал добавлять какую нибудь реализацию сертификатов.

**Comment by Username128** [comment]
Добавление сертификатов сможет позволить сохранять состояние открытых комнат и прочего чтобы это не сбрасывалось каждый раз при реконнекте? И возможно сделать отдельное окошко где будет список всех комнат + ещё возможность вешать на них пароли? И как насчёт возможности подключаться прямо по доменному имени к которому прибинден IP? Может сможете что-то из этого добавить в следующих релизах. В любом случае, вам большое спасибо за этот open-source чат!

**Comment by Nirklav** [comment]
Добавление сертификатов сможет позволить избавится от MITM атаки также с ними станет возможен процесс аутентификации и соответственно можно будет хранить информацию в бд, такую как ссесия. По этому ответ скорее всего да, можно будет сделать что бы состояние не сбрасывалось при реконнекте. Но сертификаты только первый шаг.

Доменное имена не сложно добавить в принципе.

**Comment by Username128** [comment]
Если сразу после коннекта клацнуть Enter, выбивает исключение связанное с админ командами - 


![2017-08-29_164656](https://user-images.githubusercontent.com/31361920/29824335-f7a06878-8cd9-11e7-917b-7e2813eea611.png)

**Comment by Username128** [comment]
Если сразу после коннекта нажать Enter, выбивает исключение связанное с админ командами - 

![2017-08-29_165342](https://user-images.githubusercontent.com/31361920/29824683-da09af26-8cda-11e7-9db9-c35c09751c5d.png)
