### ISSUE TITLE
настройка сервера

### ISSUE THREAD

**Issue by xerasy** [Nirklav/TCPChat#9]
Добрый день, не подскажите, как вы настроили сервер ? я запускаю consoleserver на своем вдс "ConsoleServer.exe admin 2913 2913 false" , потом в самом чате прописываю адрес вдски и порт 2913 , но получаю Attempt to connect to server... Можете немного по подробнее по настройки сервера ?

**Comment by xerasy** [comment]
вопрос исчерпан, надо было вручную открыть порт

**Comment by Nirklav** [comment]
Добрый вечер!

Не забудте открыть вместе с TCP портом также и UDP порт.
